### ISSUE TITLE
Fails to build with Ruby 1.9.3

### ISSUE THREAD

**Issue by bkabrda** [ekg2/ekg2#21]
Hi, ekg2 ruby plugin fails to build because of change in Ruby C API:

In file included from ruby_ekg.c:13:0:
ruby_ekg.h: In function 'ruby_find_script':
ruby_ekg.h:8:45: warning: variable 'slang' set but not used [-Wunused-but-set-variable]
ruby_ekg.c: In function 'ruby_command_bind':
ruby_ekg.c:109:67: error: 'struct RString' has no member named 'ptr'
ruby_ekg.c:109:48: warning: implicit declaration of function 'xstrdup' [-Wimplicit-function-declaration]
ruby_ekg.c:109:110: error: 'struct RString' has no member named 'ptr'
ruby_ekg.c: In function 'ruby_timer_bind':
ruby_ekg.c:126:110: error: 'struct RString' has no member named 'ptr'
ruby_ekg.c: In function 'ruby_watch_add':
ruby_ekg.c:151:89: error: 'struct RString' has no member named 'ptr'
ruby_ekg.c: In function 'ruby_variable_add':
ruby_ekg.c:172:50: error: 'struct RString' has no member named 'ptr'
ruby_ekg.c:175:69: error: 'struct RString' has no member named 'ptr'
ruby_ekg.c:175:104: error: 'struct RString' has no member named 'ptr'
ruby_ekg.c: In function 'ruby_handler_bind':
ruby_ekg.c:198:43: error: 'struct RString' has no member named 'ptr'
ruby_ekg.c:200:85: error: 'struct RString' has no member named 'ptr'
ruby_ekg.c: In function 'ruby_geterror':
ruby_ekg.c:252:2: warning: implicit declaration of function 'rb_frame_last_func' [-Wimplicit-function-declaration]
ruby_ekg.c:259:69: error: 'struct RString' has no member named 'ptr'
ruby_ekg.c:262:73: error: 'struct RString' has no member named 'ptr'
ruby_ekg.c:265:16: error: 'ruby_errinfo' undeclared (first use in this function)
ruby_ekg.c:265:16: note: each undeclared identifier is reported only once for each function it appears in
ruby_ekg.c:271:38: error: 'struct RArray' has no member named 'len'
ruby_ekg.c:272:85: error: 'struct RArray' has no member named 'ptr'

See http://boga.wordpress.com/2008/04/15/ruby-19-porting-notes/ for information that may help solving this bug.

Thanks,
Bohuslav.
